### ISSUE TITLE
Broken when using orderBy

### ISSUE THREAD

**Issue by appinteractive** [devoxa/prisma-relay-cursor-connection#222] opened 2021-04-25 20:55 UTC
Hey thanks for that library. Seems that I found an bug: when using with `orderBy` I only get a small set if data (16 from 101 entries). How can that be? How to fix that?

```ts
const a = await findManyCursorConnection(
  (args) => {
    return this.prisma.story.findMany({
      ...args,
      where,
      orderBy: orderBy ? { [orderBy.field]: orderBy.direction } : undefined,
      include: { authors: true, sources: true, topics: true, mood: true },
    });
  },
  () => this.prisma.story.count({ where }),
  { first, last, before, after }
);
```

**Comment by queicherius** [comment] 2021-04-26 16:44
Hey there!

I can't reproduce that behavior. It works in my server code and when added to the test cases for this package.

Could you check if the Prisma call on its own returns the entries you are expecting?

I'd also appreciate a minimal reproduction repo with the breaking schema and which fields you are ordering by.

**Comment by appinteractive** [comment] 2021-04-27 07:18
Seams to be an issue with Prisma itself:
https://github.com/prisma/prisma/issues/6337 (one of many)

As they do not use the underlaying cursor (Postgres) they are unable to determine an offset while ordering by non numeric values (uuids, names, etc.)

Therefore it seems to just not be possible. 🤷‍♂️ At least there are many tickets with that issue ore im missing something.

**Comment by queicherius** [comment] 2021-04-27 10:08
Ah, so ordering by text (in my case I ordered alphabetically by the title) worked for me because I use a string (UUID) ID and not a BigInt.

If it's a Prisma issue, I will close this one here since there's nothing we can really do about that.

**Closed by queicherius** 2021-04-27 10:08 UTC

**Comment by appinteractive** [comment] 2021-04-27 20:25
@queicherius does your case also work with null values in between? For me it does skip dozends of entries.

**Comment by queicherius** [comment] 2021-04-29 17:15
Yes, it also works for me when ordering by values that have null values. Keep in mind that all entries with null values will get ordered to the start (when ordering asc).

**Comment by appinteractive** [comment] 2021-04-29 17:17
Okay thanks for the info! Then I need to take a second look. Just one last question, are you using Postgres or another db? Any special indexes?

**Comment by queicherius** [comment] 2021-04-29 17:50
In production I use Postgres, but I did not test the null values with that (only with SQLite locally)
